#!/bin/bash


GCC_DIR=`dirname $0`

# set value for --prefix option
if [ "$1" != "" ]; then
  PREFIX=$1
else
  PLATFORM=`uname`
  if [ "${PLATFORM}" = "CYGWIN_NT-5.1" ]; then
    PREFIX=/usr/local/hexagon
  fi
  if  [ "${PLATFORM}" = "MINGW32_NT-5.1" ]; then
    PREFIX=/usr/local/hexagon-mingw
  else
    if [ "${PLATFORM}" = "Linux" ]; then
      PREFIX=${HOME}/hexagon/gnu
    else
      echo platform ${PLATFORM} not supported
      exit 1
    fi
  fi
fi


AS_FOR_TARGET=hexagon-as \
LD_FOR_TARGET=hexagon-ld \
NM_FOR_TARGET=hexagon-nm \
AR_FOR_TARGET=hexagon-ar \
CC=/pkg/qct/software/hexagon/windows-cross/gcc-3.4.5-cross/bin/i386-pc-mingw32-gcc \
CC_FOR_BUILD=gcc \
`dirname $0`/configure \
  --prefix=${PREFIX} \
  --target=hexagon \
  --host=i386-pc-mingw32 \
  --build=i686-pc-linux-gnu \
  --program-prefix=hexagon- \
  --enable-checking=assert,misc,tree,gc,rtlflag,runtime,df \
  --enable-languages=c,c++ \
  --disable-sjlj-exceptions \
  --without-fp \
  --disable-nls \
  --disable-libssp \
  ${EXP_FLAGS} \
  --with-dinkumware

