#!/bin/bash
##################################################################

# set value for --prefix option
if [ "$1" != "" ]; then
  PREFIX=$1
else
  echo Missing prefix option
  exit 1
fi

if [ "$2" != "" ]; then
  WITH_HEADERS=$2
else
  echo Missing with-header option
  exit 1
fi

export CFLAGS="-O2 -g -DUSING_NEWLIB"
export CXXFLAGS="-O2 -g -DUSING_NEWLIB"

../configure \
--prefix=${PREFIX} \
--target=hexagon \
--enable-languages=c,c++ \
--without-fp \
--disable-nls \
--with-headers=${WITH_HEADERS} \
--disable-shared \
--with-newlib 
